import { createClient } from "@/utils/supabase/server";
import { InfoIcon } from "lucide-react";
import { redirect } from "next/navigation";

export default async function ProtectedPage() {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return redirect("/sign-in");
  }

  // The code below is a temporary workaround due to the current "users" table being duplicated on
  // both the "auth" and "public" schemas, the first being from Supabase itself, while the former
  // was generated by a database migration.

  // Ideally, we should rely solely on Supabase with it's native authentication features instead
  // of having multiple "users" tables.
  const { data: temporaryUser } = await supabase
    .schema("public")
    .from("users")
    .select("id")
    .eq("email", user.email)
    .single();

  const { data: wallet } = await supabase
    .schema("public")
    .from("wallets")
    .select("circle_wallet_id")
    .eq("user_id", temporaryUser?.id)
    .single();

  return (
    <div className="flex-1 w-full flex flex-col gap-12">
      <div className="w-full">
        <div className="bg-accent text-sm p-3 px-5 rounded-md text-foreground flex gap-3 items-center">
          <InfoIcon size="16" strokeWidth={2} />
          This is a protected page that you can only see as an authenticated
          user
        </div>
      </div>
      <div className="flex flex-col gap-2 items-start">
        <h2 className="font-bold text-2xl mb-4">Your user details</h2>
        <pre className="text-xs font-mono p-3 rounded border max-h-128 overflow-auto">
          {JSON.stringify({ ...user, wallet_id: wallet?.circle_wallet_id }, null, 2)}
        </pre>
      </div>
    </div>
  );
}
